### ISSUE TITLE
For required boolean field, keep the checkbox

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#683] opened 2015-09-10 08:12 UTC

**Comment by F3L1X79** [comment] 2015-09-10 14:07
I guess you mean the checkboxes but I do agree a lot with this one :+1:

**Comment by jpetitcolas** [comment] 2015-09-10 14:12
No, radio buttons. It is either `true` or `false`. It is not a Schrödinger boolean. :)

**Comment by jpetitcolas** [comment] 2015-09-10 14:13
Oh, I see what you meant. A single checkbox: checked is true, unchecked is false. Didn't remember. Yes then. :)

**Comment by F3L1X79** [comment] 2015-09-10 14:15
Since https://github.com/marmelab/ng-admin/pull/629 , yup.

**Comment by fzaninotto** [comment] 2015-09-10 16:55
I don't agree. This should remain a true/false choice, but with a validator to refuse empty submissions.

**Comment by F3L1X79** [comment] 2015-09-11 15:34
Yes, but I think most users will prefer a checkbox over a dropdown for a required boolean - it is faster to use and way more eye friendly. 
@fzaninotto , I get your point but I think it's a shame to force developpers using a template instead of a feature they probably won't use?
Of course I won't argue anymore, it was just my point of view.

**Comment by fzaninotto** [comment] 2015-09-14 12:37
How can you validate that a checkbox control is filled?

On the other hand, nothing prevents you from using a template type, or creating you own custom type.

**Comment by jpetitcolas** [comment] 2015-09-14 12:56
For validation, using radio buttons would be fine. If no radio is checked, then the value is not filled.

**Comment by F3L1X79** [comment] 2015-09-14 13:03
Yeah you're all right, validation will still be a problem with checkboxes... Nevermind my last comments.

**Comment by fzaninotto** [comment] 2015-09-14 14:59
So I guess it's a duplicate of #527

**Closed by fzaninotto** 2015-09-14 14:59 UTC
Labels: enhancement
