### ISSUE TITLE
Edit UI: apply css class to whole row

### ISSUE THREAD

**Issue by dadmin-admin** [marmelab/ng-admin#764] opened 2015-11-06 11:51 UTC
I tried to configure field following way:
````
nga.field('url').cssClasses('hidden')
````
Since css class is applied to input div, input is hidden but label is still displayed.

How to hide/apply class to whole row?

**Comment by fzaninotto** [comment] 2015-11-06 22:17
Duplicate of #755

**Closed** 2015-11-06 22:17 UTC
