### ISSUE TITLE
Bug Report: Map will not work if its coming after other function like label

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#452] opened 2015-05-21 06:06 UTC
this will work:  nga.field('TestDefault', 'json').map(......
this will not work  nga.field('TestDefault', 'json').label("bla bgla").map(....

**Comment by fzaninotto** [comment] 2015-06-01 19:56
I can't reproduce the problem. `map()` works fine when called first, and when called after `label()`. Could you tell me which browser you're using?

**Comment by fzaninotto** [comment] 2015-06-24 19:54
No feedback, closing.

**Closed by fzaninotto** 2015-06-24 19:54 UTC
Labels: bug
