### ISSUE TITLE
Override default path

### ISSUE THREAD

**Issue by nicovak** [marmelab/ng-admin#730] opened 2015-10-12 01:09 UTC
Hello,

I'm trying to embed ng-admin in an existing angular app.
	
	.when("/admin", {
		 templateUrl: "./partials/admin/index.html",
	});

In the view I simply added:

	<div ui-view></div>

It works but I have a not found page, I only have the left menu displayed.

How can i handle the whole ng-admin in a subpath, each link seems to be broken.

![Image of the sandbox](http://i.imgur.com/qGMHGFf.png)

You can see my work [HERE](https://github.com/nicovak/sfsandbox)

Thank you :)

**Comment by fzaninotto** [comment] 2015-10-12 12:39
Duplicate of #335 - you can't for now.

**Closed by fzaninotto** 2015-10-12 12:39 UTC
