### ISSUE TITLE
Bug in ng-admin (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by akagadovskiy** [marmelab/ng-admin#582] opened 2015-07-31 12:41 UTC
Hi. I've found weird thing in ng-admin.
I used Chrome with Angular JS Batarang extension.

![vnbsn6e](https://cloud.githubusercontent.com/assets/10126017/9007482/6bc1d710-379a-11e5-8fd6-b01be6669825.png)

**Comment by fzaninotto** [comment] 2015-08-05 07:19
Very hard to debug without the use case. Could you tell us which config you use, which data is returned from the REST API, which route you're in? The best way for us to help you would be to setup a JSBin or something similar where the issue can be reproduced.

**Comment by akagadovskiy** [comment] 2015-08-05 14:20
It's demo version of application. I've just downloaded from repository. Server is demo also

**Comment by fzaninotto** [comment] 2015-08-05 14:50
Again, which page, which data? I can't reproduce this bug without sufficient feedback from you.

**Comment by akagadovskiy** [comment] 2015-08-06 06:00
![ufrdzlq](https://cloud.githubusercontent.com/assets/10126017/9104836/954947f2-3c19-11e5-9663-04c87c5b207a.png)

**Comment by fzaninotto** [comment] 2015-08-06 15:15
Nothing is logged in the console, so I guess:

- It's a side effect of your Angular Chrome extension, or
- It's not a big problem since Angular doesn't publicly log about it.

I'm closing this one. If you experience problems in using ng-admin, feel free to reopen by explaining the issue.

**Closed by fzaninotto** 2015-08-06 15:15 UTC
Labels: bug
