### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by sgimeno** [marmelab/ng-admin#424] opened 2015-05-09 14:02 UTC
I was wondering if anyone has tried to tune ng-admin for giving i18n support and translate all the HTML components "copy" texts like "Show", "Edit", etc. Any clue on which could be a good approach?

**Comment by fzaninotto** [comment] 2015-05-19 13:39
Duplicate of #169. In the meantime, all buttons support a `label` attribute.

**Closed by fzaninotto** 2015-05-19 13:39 UTC
