### ISSUE TITLE
how can i handle the nested json into the fields

### ISSUE THREAD

**Issue by Mr-Luo** [marmelab/ng-admin#539] opened 2015-06-30 10:27 UTC
[{"_id":"557f7d8bc6b7a51790000003","baseagent":{"address":"testa dd","company":"shenzhen","email":"12@111.com","license":"12222222","name":"1111111111111111","phone":"233333333"},"posted":"2015-06-26T17:47:34.441+08:00"}]

i want to get the baseagent.name,but i don't know how to do ,
i try :
nga.field('baseagent["name"]')
but that can't work.thanks

**Comment by fzaninotto** [comment] 2015-06-30 11:46
Duplicate of #525

**Closed by fzaninotto** 2015-06-30 11:46 UTC

**Comment by Mr-Luo** [comment] 2015-06-30 11:49
wow,thanks a lot.
