### ISSUE TITLE
Support for embedded entities

### ISSUE THREAD

**Issue by ihrigb** [marmelab/ng-admin#469] opened 2015-05-26 15:20 UTC
I am not to sure about the effort but embedded entities would be a great feature.

An Example:
having an entity address with fields street, zipcode and city e.g.:

    {
      "street": "Examplestreet 1",
      "zipcode": "12345",
      "city": "Examplecity"
    }

Then having another entity like company that has an embedded addess that results in json-objects like:

    {
      "name": "Example Company Inc."
      "address": {
        "street": "Examplestreet 1",
        "zipcode": "12345",
        "city": "Examplecity"
      }
    }

**Comment by fzaninotto** [comment] 2015-06-01 19:06
Duplicate of #390

**Closed by fzaninotto** 2015-06-01 19:06 UTC
