### ISSUE TITLE
Reference field false validation

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#1177] opened 2016-08-29 20:39 UTC
Validation on reference choice list during edit/create view throws an 'Invalid form' message and shows error css classes on selection of the non-default option. 

![image](https://cloud.githubusercontent.com/assets/6403652/18066371/cf81d076-6dfd-11e6-8e21-3589d8a71909.png)

Inside of maField.js `scope.getFieldValidationClass = function () {...}` the reference field value (`this.value`) is null. 

I'm not sure why validation is failing here, as there is no validation on the object itself.

Validation on the reference field is,
![image](https://cloud.githubusercontent.com/assets/6403652/18066599/a2d8fa8a-6dfe-11e6-9e23-0759ab479abf.png)

Any idea why reference field validation is failing versus choice fields?

**Comment by fzaninotto** [comment] 2016-11-18 11:10
I can't reproduce the bug. Besides, the code shows `required: false`, but the screenshot shows the required asterisk on the field...

So I'm closing this one. Feel free to reopen if you can provide a failing test case.

**Closed by fzaninotto** 2016-11-18 11:10 UTC
Labels: bug
