### ISSUE TITLE
Referenced values not displayed in edit view

### ISSUE THREAD

**Issue by stucki** [marmelab/ng-admin#557] opened 2015-07-13 16:06 UTC
Referenced fields don't show the foreign value in the edit view.

I assume this is related to #552.

To demostrate this, take a look at the demo site:
* http://ng-admin.marmelab.com:8000/#/comments/edit/3
* http://ng-admin.marmelab.com:8000/#/comments/list

As you can see, there is no post selected in the edit view, even though it is set according to the list view.

**Comment by stucki** [comment] 2015-07-13 16:07
Going back to 5e16a3c30ec5ce6f913a1dd7d393d2397a30fbd3 seems to solve the issue, so it's a regression.

**Comment by jpetitcolas** [comment] 2015-07-22 16:00
Can you try with latest version of master? I'm not able to reproduce the issue locally.

**Comment by fzaninotto** [comment] 2015-08-05 14:53
Works fine on master (and on the demo), closing. Fell free to reopen if the problem still happens to you.

**Closed by fzaninotto** 2015-08-05 14:53 UTC
