### ISSUE TITLE
one referencedlist is ignored if they reference same table

### ISSUE THREAD

**Issue by intoxicated** [marmelab/ng-admin#281] opened 2015-02-03 03:05 UTC
I have a feature that user follows other user, and db schema is following:

user:

    follower:{
        collection:'follow_table',
        via:'follower'
    },

    following:{
        collection:'follow_table',
        via:'following'
    }

follow_table:

    following: {
        model: 'user',
    },

    follower: {
        model: 'user'
    }

and I used following code to display 

    user.showView()
        .fields([
            new ReferencedList('User_follower').label('followers')
                .targetEntity(follower)
                .targetReferenceField('following')
                .targetFields([new Field('id'), 
                               new Field('follower').map(function(object){
                                    return object.display_name;
                               })]),
               new ReferencedList('User_follower').label('followings')
                .targetEntity(follower)
                .targetReferenceField('follower')
                .targetFields([new Field('id'), 
                               new Field('following').map(function(object){
                                    return object.display_name;
                               })]);

Actually there is two problems. One is first referencedlist is ignored and not execute at all. Second one is since follow table contains rows that also references to user, i attempted to use something like new 

    Reference('following').targetEntity(user).targetField(new Field('id'))

but it wouldn't work, and just using new Field('following') returned user model in object form (that's why I used map to display name). Is this expected behavior?

**Comment by fzaninotto** [comment] 2015-02-03 07:57
Well, self-references haven't been tested, so it's possible that it doesn't work for now. Marked your issue as a bug.

**Comment by jeromemacias** [comment] 2015-05-12 15:25
It should work using master version AND by defining two separate entity objects:
```js
var follower = nga.entity('user');
var following = nga.entity('user');
```

**Comment by fzaninotto** [comment] 2015-06-24 19:57
Closing as no feedback for some time. Feel free to reopen if the issue isn't solved with master.

**Closed by fzaninotto** 2015-06-24 19:57 UTC
Labels: bug
