### ISSUE TITLE
Infinitive pagination in editView/showView

### ISSUE THREAD

**Issue by thangngoc89** [marmelab/ng-admin#209] opened 2014-12-31 15:15 UTC
Just like the title. If I continue to scroll down in editView/showView . ng-admin sends requests to server.

**Comment by fzaninotto** [comment] 2015-01-08 15:25
Yep, marked as bug.

**Comment by fzaninotto** [comment] 2015-01-09 08:17
Can't reproduce the bug on master. Infinite pagination is normally off by default now.

**Comment by fzaninotto** [comment] 2015-01-14 21:29
No I can see it, reopening.

**Closed** 2015-01-14 22:33 UTC
Labels: bug
