### ISSUE TITLE
unexpected behavior when reference is null

### ISSUE THREAD

**Issue by intoxicated** [marmelab/ng-admin#315] opened 2015-02-16 05:05 UTC
I have a model that has attribute to other model, and it could be null or reference to a model. When this attribute is null, ng-admin attempted to pull out the information like this:

`http://localhost:1337/api/v1.0/refModel/null`

Where I believe if reference is null, it should not attempt to do so.

**Comment by fzaninotto** [comment] 2015-02-16 12:23
Hi Wooyoung, this has normally been fixed some time ago. Are you using the latest version of ng-admin?

**Comment by intoxicated** [comment] 2015-02-16 20:51
i got ng-admin through bower and set it to master a month ago. Should I re-download ?

**Comment by fzaninotto** [comment] 2015-02-19 08:16
Oh yes, definitely. ng-admin evolves quite fast these days.

**Comment by jpetitcolas** [comment] 2015-06-18 16:02
Can't reproduce the issue on master. Closing the issue. Feel free to re-open it if you still encounter the problem. :)

**Closed by jpetitcolas** 2015-06-18 16:02 UTC
Labels: bug
