### ISSUE TITLE
Autocomplete on a reference field causes it to appear blank.

### ISSUE THREAD

**Issue by cfatt10** [marmelab/ng-admin#903] opened 2016-01-20 18:55 UTC
I have a company/representative type relationship in my database, and in the company editionView you can change which representative is associated with the company. The field used is a reference field with remoteComplete(true) so you can search all representatives in the DB, however, when you open editionView the field appears blank but the value is still there (i.e. saving changes doesn't change the state of the company in the DB). Here's my network trace:

With remoteComplete(true)
-Loads up ng-admin (the HTML, CSS, JS, etc.)
-Sends a request for the company object. The returned company has the 'representative ID'
-Sends a request for the representative based on the 'representative ID'. Returns one object.
-Sends a request to pre-populate the drop-down field. Returns an array of objects.
-Results in me being able to search all representatives by sending more requests, but the field appears blank at the start. Clicking on the field drops down a list of representatives, showing one page's worth (in this case 30).

With remoteComplete(false)
-Loads up ng-admin (the HTML, CSS, JS, etc.)
-Sends a request for the company object. The returned company has the 'representative ID'
-Sends a request to pre-populate the drop-down field. Returns an array of objects.
-Sends a request for the representative based on the 'representative ID'. Returns one object.
-Results in me only being able to search a subset of the representatives and does not send more requests, but the field contains the current representative's name. Clicking on the field drops down the same list of representatives as before PLUS the currently associated representative (31 total).

These results were obtained using commit 58d997f on Jan 20, 2016

**Comment by hulutter** [comment] 2016-04-14 13:32
I experience exactly the same issue. Any updates on this topic?

**Comment by cfatt10** [comment] 2016-04-14 16:30
@hulutter It was acknowledged as a bug by Francois Zaninotto in the ng-admin gitter on Nov 26 2015, but nothing more has come from it. @fzaninotto

**Comment by cfatt10** [comment] 2016-04-14 16:34
Though I just replaced my build files with the most current files and it does appear to be working now.

**Comment by hulutter** [comment] 2016-04-16 17:36
@cfatt10 
Thanks for the info! I can confirm that it works with the latest master.
I think the issue can be closed.

**Comment by ericmaier** [comment] 2016-09-27 13:50
Hello. I'm experiencing this exact issue.

`nga.field('brokerId', 'reference')
            .label('Broker')
            .targetEntity(admin.getEntity('brokers'))
            .targetField(nga.field('brokerName'))
            .remoteComplete(true, {
                searchQuery: function(search) {
                    return { q: search, ref: true };
                }
            }),`

Running ng-admin version 0.9.1

I can verify that the api requests to get the initial list and a call to get the specific record for the foreign key im providing from the entity. It's odd because when I run the code above I get a list of 30 items with no value displayed (but a value is selected and im assuming it is the foreign key associated record). However, when I comment out the remoteComplete decorator the value label is displayed as expected. 

Is there a specific branch you checked out? You said master branch and it is what I am using now.

**Comment by cfatt10** [comment] 2016-09-27 16:30
I have been working on a different part of my website for the past few months, and in the meantime someone else tinkered with our ng-admin install, so I'm no longer sure what our version is. A quick Ctrl-F for 'version' on the pretty-printed minified file led to 37 matches and I'm not sure which one is the ng-admin version. If you know which line or what the surrounding code looks  I can look again for you. Other than that, my code looks a little different, but I don't think that's the problem.
`nga.field('customerID', 'reference')
              .label('Customer')
              .targetEntity(customers)
              .targetField(nga.field('fullName'))
              .attributes( {position: 'down'})
              .remoteComplete(true)
              .validation({required: true}),`

**Comment by ericmaier** [comment] 2016-09-27 18:20
You know wthose days when you make a stupid mistake and spend the entire day down a rabbit hole? Thats today for me. The API call to the specific record needs to return an object, not an array. Thank you for your response, I am all set. I need a shot!

**Comment by cfatt10** [comment] 2016-09-27 18:33
The whole object vs array is an interesting point. While it seems obvious now, I looked back at the Field Configuration documentation for the 'reference' type, and that is not made clear at all. I could see this being a stumbling point for a lot of new users.

**Comment by jpetitcolas** [comment] 2016-10-03 07:41
@cfatt10: a simpler way to get an installed package version is the following:

```
cat node_modules/ng-admin/package.json | grep version
```

Can you create a new issue to clarify your object/array point? :)

Closing the issue as it seems to be solved. Yet, perhaps a related issue: https://github.com/marmelab/ng-admin/issues/846

**Closed by jpetitcolas** 2016-10-03 07:41 UTC
