### ISSUE TITLE
Adding 'datetime' field type to field cause "invalid form" exception

### ISSUE THREAD

**Issue by doom369** [marmelab/ng-admin#854] opened 2015-12-12 19:42 UTC
I have profile with 

```
nga.field('lastModifiedTs')
```

On edit view all works and profile easily could be edited. But after I change it to 

```
nga.field('lastModifiedTs', 'datetime')
```

On edit view save I'm getting "invalid form" even I didn't change anything. Just opened from list view and pressed "Save Changes". If I choose date from date picker for that field no error and all works.

**Comment by fzaninotto** [comment] 2015-12-14 21:02
Works for me on master, can't reproduce the bug. Please retest with master. If you can provide a failing test in a JSFiddle, feel free to reopen.

**Comment by doom369** [comment] 2015-12-14 22:21
Reproduced with master.

**Comment by doom369** [comment] 2015-12-14 22:47
@fzaninotto I was able to localize a bit. It happens if field is int with timestamp. For instance 1450125921836 did you check it? datetime field doesn't accept any date if it has seconds, hours or minutes. I can't reopen.

**Comment by fzaninotto** [comment] 2015-12-15 08:03
OK, now I can reproduce the bug. Reopening.

**Comment by fzaninotto** [comment] 2015-12-15 08:55
This is probably due to a bug in Angular ui's datepicker directive. We're using a not up-to-date version, but upgrading it means a lot of work and testing.

In the meantime, I suggest you add an element transformer to turn your timestamp into a string (e.g. "2015-12-08T23:00:00.000Z").

**Comment by doom369** [comment] 2015-12-15 11:15
Ok. Thank you. I'll try that way.

**Comment by Kmaschta** [comment] 2016-11-18 21:54
No update on this for a while, I close it for now.
Feel free to reopen if you are still facing the issue.

**Closed by Kmaschta** 2016-11-18 21:54 UTC
Labels: bug
