### ISSUE TITLE
authentication walkthrough

### ISSUE THREAD

**Issue by cmnstmntmn** [marmelab/ng-admin#682] opened 2015-09-10 07:15 UTC
beeing new to angular i found ng-admin a great tool to start working with.

one major starting issue is how i manage forms and controllers to handle jwt user authentication (client side). i saw examples in here, but there are out of the context; or so they seemd to me.

does any of you can say which the steps are to implement it and can share
thank you

**Comment by fzaninotto** [comment] 2015-09-10 07:38
Please avoid opening too many issues, or we'll just end up ignoring your requests. Duplicate of #603.

**Closed by fzaninotto** 2015-09-10 07:38 UTC
