### ISSUE TITLE
Add href property for new / most popular <a> tags

### ISSUE THREAD

**Issue by dadmin-admin** [marmelab/ng-admin#783] opened 2015-11-13 12:11 UTC
Right now each `<a>` doesn't have `href` property. It means that I can't copy link / open it in a new window. I understand that it may be hard to add `href` to all existing links but I think that it's better to start doing it for new features / main links - it will improve usability

**Comment by fzaninotto** [comment] 2015-11-13 20:26
Duplicate of #775

**Closed by fzaninotto** 2015-11-13 20:26 UTC
