### ISSUE TITLE
Handling pre-populated fields in case of relations

### ISSUE THREAD

**Issue by SaiNageswarS** [marmelab/ng-admin#700] opened 2015-09-21 19:10 UTC
ng-admin is a very useful and awesome framework. However, in case of relations, ng-admin expects id of the referenced fields. Could anyone help me how to deal in case the referenced fields are pre-populated. For e.g. 

{
    "categories": [
      {
        "name": "Shirt",
        "gender": "unisex",
        "id": 2,
        "createdAt": "2015-09-20T15:46:56.000Z",
        "updatedAt": "2015-09-20T15:46:56.000Z",
        "parentCategory": null
      }
    ],
    "price": {
      "price": 1200,
      "commission": 0.25,
      "discount": 0.2,
      "id": 1,
      "createdAt": "2015-09-20T15:48:51.000Z",
      "updatedAt": "2015-09-20T16:07:27.000Z"
    },
    "designer": {
      "name": "HSR Designer",
      "phone": "9620253965",
      "id": 1,
      "createdAt": "2015-09-20T16:03:49.000Z",
      "updatedAt": "2015-09-20T16:03:49.000Z",
      "address": 1
    },
    "name": "Flying Wheel",
    "description": null,
    "customizable": true,
    "id": 1,
    "createdAt": "2015-09-20T15:48:51.000Z",
    "updatedAt": "2015-09-20T16:07:27.000Z"
  }

Here, categories is a referenced field and is pre-populated. Although it is easy displaying in listview using map, however, in editview it seems very difficult as ng-admin tries getting detail of each object sending category/{json} as request.

Create view works fine as expected as it fetches all possible fields in select dropdown.

Thanks in advance.

**Comment by fzaninotto** [comment] 2015-09-21 20:58
Duplicate of #241

**Closed by fzaninotto** 2015-09-21 20:58 UTC
