### ISSUE TITLE
Reference to nested entity doesn't work in listView

### ISSUE THREAD

**Issue by Irrealist** [marmelab/ng-admin#837] opened 2015-12-08 22:36 UTC
Using the following field in a listView:

``` javascript
nga.field('parent.id', 'reference')
    .label('Post')
    .targetEntity(post)
    .targetField(nga.field('title'))
```

results in an empty field in every row. The field works fine in creation, show, and edit views.
It works fine if the reference is to a non-nested field, e.g. "parent_id".

**Comment by mdhooge** [comment] 2015-12-28 16:08
The workaround I have found is:

```js
  RestangularProvider.addElementTransformer( 'entities', false, function( entity ) {
    if( entity.parent instanceof Object ) {
      entity.parent__id = entity.parent.id;
    }
    return entity;
  });
```

And then you reference `parent__id` instead of the nested entity. This works fine for the listView but not the dashboard…

**Comment by mdhooge** [comment] 2015-12-30 15:29
Some more experiments: The problem is with any nested fields, not only with reference.

It seems that everything after the first dot is "removed". For example, when trying to sort on a column with a nested field, everything after the first dot isn't received by the REST server.

Finally, for nested fields that aren't references, it is possible to use a template.

My 2 cents
Michel

**Comment by NoZiL** [comment] 2016-09-05 16:40
I encountered the same issue with listView, nested reference works with creationView though.

**Comment by Kmaschta** [comment] 2016-11-18 22:02
It's a duplicate of the issue #1229.
I close this one to keep track of only one open issue.

**Closed by Kmaschta** 2016-11-18 22:02 UTC
Labels: duplicate
