### ISSUE TITLE
reference_many Field Type overflows in show view

### ISSUE THREAD

**Issue by enorrmann** [marmelab/ng-admin#1052] opened 2016-04-27 17:24 UTC
but in the edit view it is working fine

wrong: http://i.imgur.com/nXfmA88.png

right: http://i.imgur.com/pdq0vkv.png

**Comment by Phocea** [comment] 2017-01-09 13:14
@jpetitcolas @Kmaschta What do we do with this? I cannot reproduce the reported bug by @enorrmann .
Shall we close it?

**Comment by jpetitcolas** [comment] 2017-01-09 13:55
Let's close it for now. @enorrmann, feel free to re-open the issue if you still encounter it.

**Closed by jpetitcolas** 2017-01-09 13:55 UTC
Labels: bug
