### ISSUE TITLE
CrudModule missing humane

### ISSUE THREAD

**Issue by lukemarsh** [marmelab/ng-admin#292] opened 2015-02-05 08:39 UTC
I have a set up a project using a yeoman generator: https://github.com/aaronallport/generator-angular-require

When I run grunt test I get the error "CrudModule missing humane"

I have installed the master branch of ng-admin using bower and I can see that humane is in the bower components directory. Any ideas?

**Comment by fzaninotto** [comment] 2015-02-05 21:16
No idea. @manuquentin, any insight?

**Comment by lukemarsh** [comment] 2015-02-12 09:07
If I comment out line 76 in CrudModule.js and build ng-admin then include it in my project, when i run my tests it works...

@manuquentin any ideas?

**Comment by lukemarsh** [comment] 2015-02-13 13:22
@fzaninotto I have replaced humane with alertify and it fixes the issue here. I'd like to create a pull request so I can show you the changes. Would you mind adding me as a contributor?

**Comment by fzaninotto** [comment] 2015-02-16 18:08
I can't reproduce the issue. Maybe a problem with yeoman? 

Can you post a simple test project triggering the bug as a Gist to let us reproduce the issue?

**Comment by easel** [comment] 2015-02-26 02:04
I think this is a humane issue, it tries to be "smart" about being an AMD module when asked and I don't think it works all the time. If you're having the same problem I did, you can see that the problem is that humane isn't properly exporting itself by running require('humane') from your javascript console, it will return undefined instead of an object.

I ended up resolving it by replacing the crazy module header in humane.js with a simple define(function(require) {

**Comment by fzaninotto** [comment] 2015-02-27 08:31
Could you open an issue on the humane repository? 
we have no such problems with other dependencies.

**Comment by jpetitcolas** [comment] 2015-06-18 16:04
We refactored our build process several weeks ago, using Webpack instead of requirejs. Can you try again if you still encounter the issue?

**Comment by fzaninotto** [comment] 2015-07-13 09:30
No news for some time, closing.

**Closed by fzaninotto** 2015-07-13 09:30 UTC
