### ISSUE TITLE
'datetime' field doesn't accept dates that has minutes, hours, seconds. Only '00:00:00' value allowed.

### ISSUE THREAD

**Issue by doom369** [marmelab/ng-admin#860] opened 2015-12-14 22:53 UTC
Reopening https://github.com/marmelab/ng-admin/issues/854

2015-12-15 00:00:00 - accepted
2015-12-15 11:00:00 - not allowed (invalid form)

**Comment by fzaninotto** [comment] 2015-12-15 11:17
Duplicate of #854

**Closed by fzaninotto** 2015-12-15 11:17 UTC
