### ISSUE TITLE
Choice field doesn't appear to work.

### ISSUE THREAD

**Issue by ashleydavis** [marmelab/ng-admin#1075] opened 2016-05-19 05:26 UTC
I've been trying to get a choices field into my admin page, specifically in the _creation view_.

I've tried the example from the documentation:

```
 nga.field('country', 'choice')
      .choices([
        { value: 'FR', label: 'France' },
        { value: 'US', label: 'USA' },
      ]),           
```

It causes the following error when opening the _create_ page:

angular.js:13550 TypeError: t.choices is not a function
    at pre (http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:15:2545)
    at http://localhost:3000/bower_components/angular/angular.js:9688:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9694:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9072:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9088:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9088:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:8277:30)

**Comment by sam2x** [comment] 2016-05-19 23:09
Huh. Can you expose your whole entity definition ?

**Comment by ashleydavis** [comment] 2016-05-20 00:47
I've created repo that demonstrates the problem. These most recent commit adds a _choice_ field that causes the issue.

Clone this: 
  https://github.com/Real-Serious-Games/admin-portal-template

Install dependencies:

  npm install
  cd Client
  bower install
  cd ..\

Run the server:

  cd src
  node server.js

Navigate to the customer creation screen:

  http://localhost:3000/your-secret-key/#/customers/create

The following error should appear in your browser console:

  angular.js:13550 TypeError: t.choices is not a function


Note that this issue only happens in the most recent commit. If you revert back to the prior commit and go to the customer creation screen there is no issue.

**Comment by ashleydavis** [comment] 2016-05-20 01:04
The code that defines the entities can be found in _customize.js_.

**Comment by dspasojevic** [comment] 2016-05-27 06:59
This looks to be the same issue as https://github.com/marmelab/ng-admin/issues/778. I don't think that the fix for that issue has been released as part of 0.9.x.

Did you find a solution to this issue on 0.9.1?

**Comment by jpetitcolas** [comment] 2016-10-03 08:18
Can you have a look on last master version and check if you can still reproduce the issue?

**Comment by Phocea** [comment] 2016-11-18 13:52
No feedback since @jpetitcolas  last request, closing...
Please feel free to reopen if required

**Closed by Phocea** 2016-11-18 13:52 UTC
