### ISSUE TITLE
[Help] How I can do this in "creationView" or "editionView"?

### ISSUE THREAD

**Issue by vcenturion** [marmelab/ng-admin#781] opened 2015-11-12 19:56 UTC
![relaciones](https://cloud.githubusercontent.com/assets/11774045/11129472/3e601bd6-895e-11e5-8d34-255370cf5119.png)

Thanks.

**Comment by fzaninotto** [comment] 2015-11-12 20:45
Duplicate of #770 (cf https://github.com/marmelab/ng-admin/issues/770#issuecomment-156228512)

**Closed by fzaninotto** 2015-11-12 20:45 UTC
